In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

# custom font defs
title_font = {'family': 'times new roman', 'color': 'darkred','weight': 'bold','size': 22}
axis_font  = {'family': 'times new roman', 'color': 'darkred','weight': 'bold','size': 16 }

# import csv with needed columns
usecols = ['PRIMARY_KEY', 'STATE', 'YEAR', 'TOTAL_REVENUE', 'TOTAL_EXPENDITURE', 
           'AVG_MATH_4_SCORE', 'AVG_MATH_8_SCORE','AVG_READING_4_SCORE', 'AVG_READING_8_SCORE']
# import from clean csv data
df = pd.read_csv('states_all_clean.csv', usecols = usecols)
df.columns
df = df.set_index('PRIMARY_KEY')
df.columns
df

     0    1   2
0  1.0  6.5 NaN
1  1.0  NaN NaN
2  NaN  NaN NaN
3  NaN  6.5 NaN

     0    1
0  1.0  6.5
1  1.0  NaN
2  NaN  NaN
3  NaN  6.5